name: CI Pipeline

on:
  push:
    branches: [ "main" ]

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ kesava77 }}
          password: ${{ Kesava@77 }}

      - name: Build Docker image
        run: |
          docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/port-demo-app:latest .

      - name: Push Docker image
        run: |
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/port-demo-app:latest

      - name: Run container for verification
        run: |
          docker run -d -e APP_PORT=8000 -p 8000:8000 --name test-app \
            ${{ secrets.DOCKERHUB_USERNAME }}/port-demo-app:latest
          sleep 5
          curl http://localhost:8000/health
